# .github/workflows/build-broke.yml
name: Build Broke IPA with ad-hoc entitlements
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build archive (UNsigniert, aber Codesign zulassen)
        run: |
          xcodebuild \
            -scheme Broke \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/Broke.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            archive

      - name: **Ad-hoc sign the .app with entitlements**
        run: |
          APP_PATH="build/Broke.xcarchive/Products/Applications/Broke.app"
          /usr/bin/codesign --force --sign - \
            --entitlements Broke/Broke.entitlements \
            --timestamp=none "$APP_PATH"

      - name: Package IPA
        run: |
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          zip -r Broke-unsigned.ipa Payload

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Broke
          path: Broke-unsigned.ipa
