# .github/workflows/build-broke.yml
name: Build Broke IPA (ad-hoc signed)

on:
  workflow_dispatch: {}          # manueller Start

jobs:
  build:
    runs-on: macos-14            # Xcode-Runner

    steps:
    # ---------------------------------------------------------------------
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Resolve SwiftPM dependencies
      run: xcodebuild -resolvePackageDependencies

    # ---------------------------------------------------------------------
    - name: Archive (unsigned)
      run: |
        xcodebuild \
          -scheme Broke \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/Broke.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ENABLE_BITCODE=NO \
          archive

    # ---------------------------------------------------------------------
    - name: Ad-hoc codesign
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"
        /usr/bin/codesign --force --sign - \
          --entitlements Broke/Broke.entitlements \
          --timestamp=none "$APP"

    # ---------------------------------------------------------------------
    - name: Package IPA
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"
        mkdir -p Payload
        cp -R "$APP" Payload/
        zip -qr Broke-unsigned.ipa Payload

    # ---------------------------------------------------------------------
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: Broke
        path: Broke-unsigned.ipa
