# .github/workflows/build-broke.yml
# Erstellt eine unsignierte Broke-IPA, signiert sie ad-hoc mit Entitlements
# und prüft im Debug-Step direkt, welche Entitlements im .app-Binary stecken.

name: Build Broke IPA (ad-hoc signed + debug)

on:
  workflow_dispatch: {}  # Manueller Trigger im Actions-Tab

jobs:
  build:
    runs-on: macos-14    # GitHub-Runner mit Xcode 15.x

    steps:
    # 1) Quellcode einchecken
    - name: Checkout source
      uses: actions/checkout@v4

    # 2) Swift-Package-Dependencies auflösen (falls vorhanden)
    - name: Resolve SwiftPM dependencies
      run: xcodebuild -resolvePackageDependencies

    # 3) Archiv ohne Zertifikat bauen
    - name: Archive (unsigned)
      run: |
        xcodebuild \
          -scheme Broke \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/Broke.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ENABLE_BITCODE=NO \
          archive

    # 4) Ad-hoc-Signatur mit Entitlements
    - name: Ad-hoc codesign with entitlements
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"
        /usr/bin/codesign --force --sign - \
          --entitlements Broke/Broke.entitlements \
          --timestamp=none "$APP"

    # 5) DEBUG: Entitlements im .app anzeigen
    - name: Verify entitlements in .app
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"
        echo "=== ENTITLEMENTS DUMP ==="
        /usr/bin/codesign -d --entitlements :- "$APP"
        echo "========================="

    # 6) IPA packen
    - name: Package IPA
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"
        mkdir -p Payload
        cp -R "$APP" Payload/
        zip -qr Broke-unsigned.ipa Payload

    # 7) IPA als Artifact hochladen
    - name: Upload IPA artefact
      uses: actions/upload-artifact@v4
      with:
        name: Broke
        path: Broke-unsigned.ipa
