name: Build Broke IPA (ad-hoc signed)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Resolve SPM deps
      run: xcodebuild -resolvePackageDependencies

    - name: Archive (unsigned)
      run: |
        xcodebuild \
          -scheme Broke \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/Broke.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ENABLE_BITCODE=NO \
          archive

    - name: Ad-hoc codesign
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"
        /usr/bin/codesign --force --sign - \
          --entitlements Broke/Broke.entitlements \
          --timestamp=none "$APP"

    - name: Package IPA  # <- Fix hier
      run: |
        APP="
