name: Build Broke IPA (ad-hoc signed)

on:
  workflow_dispatch: {}          # manueller Startknopf

jobs:
  build:
    runs-on: macos-14            # GitHub-Runner mit Xcode 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1) Archiv ohne Zertifikatszwang bauen
    - name: Archive
      run: |
        xcodebuild \
          -scheme Broke \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/Broke.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ENABLE_BITCODE=NO \
          archive

    # 2) Einmal ad-hoc signieren – ENTITLEMENTS WERDEN ÜBERNOMMEN!
    - name: Ad-hoc codesign
      run: |
        APP="$PWD/build/Broke.xcarchive/Products/Applications/Broke.app"
        /usr/bin/codesign --force --sign - \
          --entitlements Broke/Broke.entitlements \
          --timestamp=none "$APP"

    # 3) IPA verpacken
        - name: Package IPA
      run: |
        APP="build/Broke.xcarchive/Products/Applications/Broke.app"  # Pfad erneut definieren
        mkdir -p Payload
        cp -R "$APP" Payload/
        cd Payload
        zip -qr ../Broke-unsigned.ipa .


    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: Broke
        path: Broke-unsigned.ipa
